---
- include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution | lower }}.yml"
    - "vars/{{ ansible_os_family | lower }}.yml"
    - "vars/default.yml"

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: repository

- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: repository

